# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      - python: 2.7
      - python: 3.4
      - python: 3.5
      - python: 3.6
      - python: 3.7-dev
      - python: pypy
      - python: 3.6
        env: TOX_ENV=flake8

install:
  - pip install tox-travis

script:
  - tox

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
